# Generated by Django 4.1.2 on 2022-11-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btest', '0003_alter_bb_options_alter_rubric_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exponat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Экспонаты',
                'verbose_name_plural': 'Экспонаты',
                'ordering': ['name'],
            },
        ),
    ]
