# Generated by Django 4.1.2 on 2022-12-01 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btest', '0007_zal'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='zal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='btest.zal', verbose_name='Выставочный зал'),
        ),
    ]
